/*
 * App URI: mypage
 * Source Location: mypage.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("mypage", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * mypage.js
			 * Created at 2023. 8. 4. 오전 9:40:38.
			 *
			 * @author USER
			 ************************************************/;
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("grp1");
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			group_1.setLayout(responsiveXYLayout_1);
			(function(container){
				var tabFolder_1 = new cpr.controls.TabFolder();
				tabFolder_1.tabIndex = 3;
				
				var tabItem_1 = (function(tabFolder){
					var tabItem_1 = new cpr.controls.TabItem();
					tabItem_1.text = "MYPAGE";
					var group_2 = new cpr.controls.Container("grp2");
					var xYLayout_2 = new cpr.controls.layouts.XYLayout();
					group_2.setLayout(xYLayout_2);
					(function(container){
						var group_3 = new cpr.controls.Container("grp5");
						var formLayout_1 = new cpr.controls.layouts.FormLayout();
						formLayout_1.scrollable = false;
						formLayout_1.topMargin = "0px";
						formLayout_1.rightMargin = "0px";
						formLayout_1.bottomMargin = "0px";
						formLayout_1.leftMargin = "0px";
						formLayout_1.horizontalSpacing = "5px";
						formLayout_1.verticalSpacing = "5px";
						formLayout_1.setColumns(["1fr", "100px", "200px", "100px", "1fr"]);
						formLayout_1.setRows(["1fr", "25px", "25px", "25px", "25px", "25px", "25px", "25px", "50px", "50px", "50px", "1fr"]);
						group_3.setLayout(formLayout_1);
						(function(container){
							var output_1 = new cpr.controls.Output();
							output_1.value = "ID";
							output_1.style.css({
								"text-align" : "center"
							});
							container.addChild(output_1, {
								"colIndex": 1,
								"rowIndex": 1,
								"horizontalAlign": "center"
							});
							var output_2 = new cpr.controls.Output();
							output_2.value = "PASSWORD";
							output_2.style.css({
								"text-align" : "center"
							});
							container.addChild(output_2, {
								"colIndex": 1,
								"rowIndex": 2,
								"horizontalAlign": "center"
							});
							var output_3 = new cpr.controls.Output();
							output_3.value = "주소";
							output_3.style.css({
								"text-align" : "center"
							});
							container.addChild(output_3, {
								"colIndex": 1,
								"rowIndex": 3,
								"horizontalAlign": "center"
							});
							var output_4 = new cpr.controls.Output();
							output_4.value = "이름";
							output_4.style.css({
								"text-align" : "center"
							});
							container.addChild(output_4, {
								"colIndex": 1,
								"rowIndex": 4,
								"horizontalAlign": "center"
							});
							var output_5 = new cpr.controls.Output();
							output_5.value = "생년월일";
							output_5.style.css({
								"text-align" : "center"
							});
							container.addChild(output_5, {
								"colIndex": 1,
								"rowIndex": 5,
								"horizontalAlign": "center"
							});
							var output_6 = new cpr.controls.Output();
							output_6.value = "이메일";
							output_6.style.css({
								"text-align" : "center"
							});
							container.addChild(output_6, {
								"colIndex": 1,
								"rowIndex": 6,
								"horizontalAlign": "center"
							});
							var output_7 = new cpr.controls.Output();
							output_7.value = "휴대폰 번호";
							output_7.style.css({
								"text-align" : "center"
							});
							container.addChild(output_7, {
								"colIndex": 1,
								"rowIndex": 7,
								"horizontalAlign": "center"
							});
							var inputBox_1 = new cpr.controls.InputBox("ipb1");
							container.addChild(inputBox_1, {
								"colIndex": 2,
								"rowIndex": 1
							});
							var inputBox_2 = new cpr.controls.InputBox("ipb2");
							inputBox_2.secret = true;
							container.addChild(inputBox_2, {
								"colIndex": 2,
								"rowIndex": 2
							});
							var inputBox_3 = new cpr.controls.InputBox("ipb3");
							container.addChild(inputBox_3, {
								"colIndex": 2,
								"rowIndex": 3
							});
							var inputBox_4 = new cpr.controls.InputBox("ipb4");
							container.addChild(inputBox_4, {
								"colIndex": 2,
								"rowIndex": 4
							});
							var inputBox_5 = new cpr.controls.InputBox("ipb6");
							container.addChild(inputBox_5, {
								"colIndex": 2,
								"rowIndex": 6
							});
							var button_1 = new cpr.controls.Button("btn1");
							button_1.value = "패스워드변경";
							container.addChild(button_1, {
								"colIndex": 3,
								"rowIndex": 2
							});
							var maskEditor_1 = new cpr.controls.MaskEditor("mse1");
							maskEditor_1.mask = "XXX-XXXX-XXXX";
							container.addChild(maskEditor_1, {
								"colIndex": 2,
								"rowIndex": 7
							});
							var dateInput_1 = new cpr.controls.DateInput("dti1");
							container.addChild(dateInput_1, {
								"colIndex": 2,
								"rowIndex": 5
							});
							var button_2 = new cpr.controls.Button("btn2");
							button_2.value = "수정하기";
							container.addChild(button_2, {
								"colIndex": 2,
								"rowIndex": 9
							});
						})(group_3);
						container.addChild(group_3, {
							"width": "962px",
							"height": "779px",
							"left": "calc(50% - 481px)",
							"top": "calc(50% - 389px)"
						});
					})(group_2);
					tabItem_1.content = group_2;
					return tabItem_1;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_1);
				
				var tabItem_2 = (function(tabFolder){
					var tabItem_2 = new cpr.controls.TabItem();
					tabItem_2.text = "MYPLAN";
					var group_4 = new cpr.controls.Container("grp3");
					var xYLayout_3 = new cpr.controls.layouts.XYLayout();
					group_4.setLayout(xYLayout_3);
					tabItem_2.content = group_4;
					return tabItem_2;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_2);
				
				var tabItem_3 = (function(tabFolder){
					var tabItem_3 = new cpr.controls.TabItem();
					tabItem_3.text = "플랜 게시판";
					var group_5 = new cpr.controls.Container("grp4");
					var xYLayout_4 = new cpr.controls.layouts.XYLayout();
					group_5.setLayout(xYLayout_4);
					tabItem_3.content = group_5;
					return tabItem_3;
				})(tabFolder_1);
				tabFolder_1.addTabItem(tabItem_3);
				tabFolder_1.setSelectedTabItem(tabItem_1);
				container.addChild(tabFolder_1, {
					positions: [
						{
							"media": "all and (min-width: 1024px)",
							"top": "0px",
							"right": "0px",
							"bottom": "0px",
							"left": "0px"
						}, 
						{
							"media": "all and (min-width: 500px) and (max-width: 1023px)",
							"top": "0px",
							"right": "0px",
							"bottom": "0px",
							"left": "0px"
						}, 
						{
							"media": "all and (max-width: 499px)",
							"top": "0px",
							"right": "0px",
							"bottom": "0px",
							"left": "0px"
						}
					]
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0px",
				"right": "0px",
				"bottom": "0px",
				"left": "0px"
			});
		}
	});
	app.title = "mypage";
	cpr.core.Platform.INSTANCE.register(app);
})();
