/*
 * App URI: planner
 * Source Location: planner.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.4584), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("planner", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/************************************************
			 * planner.js
			 * Created at 2023. 8. 3. 오후 2:50:01.
			 *
			 * @author iedl9
			 ************************************************/

			/*
			 * "저장" 버튼에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onButtonClick(e){
				var button = e.control;

			};
			// End - User Script
			
			// Header
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var textArea_1 = new cpr.controls.TextArea("txa1");
				textArea_1.value = "제주도 지역 검색";
				textArea_1.style.css({
					"text-align" : "center"
				});
				container.addChild(textArea_1, {
					"top": "0px",
					"bottom": "0px",
					"left": "0px",
					"width": "290px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "검색";
				container.addChild(button_1, {
					"top": "0px",
					"right": "0px",
					"width": "100px",
					"height": "20px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "41px",
				"left": "20px",
				"width": "400px",
				"height": "22px"
			});
			
			var group_2 = new cpr.controls.Container();
			var xYLayout_3 = new cpr.controls.layouts.XYLayout();
			group_2.setLayout(xYLayout_3);
			(function(container){
				var textArea_2 = new cpr.controls.TextArea("txa2");
				textArea_2.value = "플래너 제목 :";
				textArea_2.style.css({
					"text-align" : "center"
				});
				container.addChild(textArea_2, {
					"top": "0px",
					"bottom": "0px",
					"left": "0px",
					"width": "185px"
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				container.addChild(inputBox_1, {
					"top": "0px",
					"right": "0px",
					"left": "184px",
					"height": "22px"
				});
			})(group_2);
			container.addChild(group_2, {
				"top": "20px",
				"left": "20px",
				"width": "848px",
				"height": "22px"
			});
			
			var group_3 = new cpr.controls.Container();
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.horizontalSpacing = "25px";
			formLayout_1.verticalSpacing = "25px";
			formLayout_1.setColumns(["50px", "50px"]);
			formLayout_1.setRows(["25px"]);
			group_3.setLayout(formLayout_1);
			(function(container){
				var button_2 = new cpr.controls.Button();
				button_2.value = "저장";
				container.addChild(button_2, {
					"colIndex": 0,
					"rowIndex": 0,
					"verticalAlign": "top"
				});
				var button_3 = new cpr.controls.Button();
				button_3.value = "취소";
				container.addChild(button_3, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_3);
			container.addChild(group_3, {
				"top": "14px",
				"left": "867px",
				"width": "150px",
				"height": "33px"
			});
			
			var group_4 = new cpr.controls.Container();
			var xYLayout_4 = new cpr.controls.layouts.XYLayout();
			group_4.setLayout(xYLayout_4);
			(function(container){
				var linkedComboBox_1 = new cpr.controls.LinkedComboBox("lcb1");
				container.addChild(linkedComboBox_1, {
					"top": "0px",
					"left": "0px",
					"width": "120px",
					"height": "20px"
				});
			})(group_4);
			container.addChild(group_4, {
				"top": "73px",
				"left": "20px",
				"width": "120px",
				"height": "694px"
			});
			
			var group_5 = new cpr.controls.Container();
			var xYLayout_5 = new cpr.controls.layouts.XYLayout();
			group_5.setLayout(xYLayout_5);
			(function(container){
				var grid_1 = new cpr.controls.Grid("grd2");
				grid_1.init({
					"columns": [{"width": "100px"}],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "여행지 목록";
							}
						}]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
							}
						}]
					}
				});
				container.addChild(grid_1, {
					"top": "0px",
					"left": "0px",
					"width": "140px",
					"height": "694px"
				});
			})(group_5);
			container.addChild(group_5, {
				"top": "73px",
				"left": "278px",
				"width": "140px",
				"height": "694px"
			});
			
			var group_6 = new cpr.controls.Container();
			var xYLayout_6 = new cpr.controls.layouts.XYLayout();
			group_6.setLayout(xYLayout_6);
			(function(container){
				var grid_2 = new cpr.controls.Grid("grd1");
				grid_2.init({
					"columns": [{"width": "167px"}],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
								cell.text = "선택한 여행지 목록";
							}
						}]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [{
							"constraint": {"rowIndex": 0, "colIndex": 0},
							"configurator": function(cell){
							}
						}]
					}
				});
				container.addChild(grid_2, {
					"top": "0px",
					"left": "0px",
					"width": "140px",
					"height": "694px"
				});
			})(group_6);
			container.addChild(group_6, {
				"top": "73px",
				"left": "139px",
				"width": "140px",
				"height": "694px"
			});
		}
	});
	app.title = "planner";
	cpr.core.Platform.INSTANCE.register(app);
})();
